





FROM python:3.9-slim
RUN groupadd -r customuser && useradd -r -g customuser customuser

WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .

RUN chown -R customuser:customuser /app
USER customuser

EXPOSE 5000
CMD ["python", "app.py"]

